services:
  - type: web
    name: sbs-vision
    runtime: static
    buildCommand: bun install --no-save && bun run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_SUPABASE_QUOTES_BUCKET
        value: quotes
